	real*8 function evalspline(xeval,n_good,brkpts,yout,cout)
!
! Evalutes the spline generated by cubgcv.f
!
	implicit none

	include 'include.inc'

	real*8  xeval,dx
	real*8  brkpts(max_pnts),yout(max_pnts),cout(max_pnts,3)
	integer i,mflag			!output from interv
	integer n_good

	call interv(brkpts,n_good,xeval,i,mflag)
	if (mflag.eq.0) then
	  dx=xeval-brkpts(i)
	  evalspline=yout(i)+cout(i,1)*dx+cout(i,2)*dx*dx/2.+
     &               cout(i,3)*dx*dx*dx/6.
	else if (mflag.eq.-1) then	! below lowest value
	  evalspline = yout(1)
	else if (mflag.eq.1) then	!above highest value
	  evalspline = yout(n_good)
	endif
!	write(6,*) brkpts
!	write(6,*) 'xeval,mflag,i,evalspline=',xeval,mflag,i,evalspline

	end
