#!/bin/tcsh
do50degallboost.sh;
do40degallboost.sh;
do46degallboost.sh;
do18degallboost.sh;
do22degallboost.sh;
do24degallboost.sh;
do26degallboost.sh;
do29degallboost.sh;
do32degallboost.sh;
do36degallboost.sh;
